[package]
name = "common"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
tokio = { workspace = true }
serde_yml = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
mlua = { workspace = true }
bumpalo = { workspace = true }
bitcode = { workspace = true }
toml = { workspace = true }
lz4_flex = { workspace = true }
arc-swap = { workspace = true }
